version: "3.8"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  db:
    image: postgres:16
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_DB: arxatecservice
      POSTGRES_USER: arxatec
      POSTGRES_PASSWORD: arxatec
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
