export const CATEGORIES = ["civil", "laboral", "familiar", "penal"];
export const STATUSES = ["abierto", "en_progreso", "cerrado", "archivado"];
export const CLIENT_CASES_LIST = [
  {
    title: "Divorcio contencioso",
    status: "abierto",
    category: "familiar",
    urgency: "alta",
    description: "Proceso de divorcio con disputa de bienes",
  },
  {
    title: "Pensión alimenticia",
    status: "abierto",
    category: "familiar",
    urgency: "alta",
    description: "Solicitud de pensión alimenticia para menores",
  },
  {
    title: "Custodia de menores",
    status: "abierto",
    category: "familiar",
    urgency: "media",
    description: "Disputa por custodia compartida",
  },
  {
    title: "Despido injustificado",
    status: "abierto",
    category: "laboral",
    urgency: "alta",
    description: "Reclamación por despido sin causa justa",
  },
  {
    title: "Accidente laboral",
    status: "abierto",
    category: "laboral",
    urgency: "media",
    description: "Indemnización por accidente en el trabajo",
  },
  {
    title: "Horas extras no pagadas",
    status: "abierto",
    category: "laboral",
    urgency: "baja",
    description: "Reclamación de horas extras trabajadas",
  },
  {
    title: "Contrato de arrendamiento",
    status: "abierto",
    category: "civil",
    urgency: "media",
    description: "Disputa por contrato de alquiler",
  },
  {
    title: "Daños y perjuicios",
    status: "abierto",
    category: "civil",
    urgency: "alta",
    description: "Reclamación por daños materiales",
  },
  {
    title: "Incumplimiento de contrato",
    status: "abierto",
    category: "civil",
    urgency: "media",
    description: "Incumplimiento de contrato comercial",
  },
  {
    title: "Herencia y sucesiones",
    status: "abierto",
    category: "civil",
    urgency: "baja",
    description: "Proceso de sucesión testamentaria",
  },
  {
    title: "Denuncia por robo",
    status: "abierto",
    category: "penal",
    urgency: "alta",
    description: "Denuncia penal por robo con violencia",
  },
  {
    title: "Estafa comercial",
    status: "abierto",
    category: "penal",
    urgency: "media",
    description: "Denuncia por estafa en transacción comercial",
  },
  {
    title: "Violencia doméstica",
    status: "abierto",
    category: "penal",
    urgency: "alta",
    description: "Denuncia por violencia intrafamiliar",
  },
  {
    title: "Régimen de visitas",
    status: "abierto",
    category: "familiar",
    urgency: "media",
    description: "Establecimiento de régimen de visitas",
  },
  {
    title: "Adopción",
    status: "abierto",
    category: "familiar",
    urgency: "baja",
    description: "Proceso de adopción de menor",
  },
  {
    title: "Hostigamiento laboral",
    status: "abierto",
    category: "laboral",
    urgency: "alta",
    description: "Denuncia por acoso en el trabajo",
  },
  {
    title: "Liquidación de beneficios",
    status: "abierto",
    category: "laboral",
    urgency: "media",
    description: "Reclamación de beneficios sociales",
  },
  {
    title: "Desalojo",
    status: "abierto",
    category: "civil",
    urgency: "alta",
    description: "Proceso de desalojo de inmueble",
  },
  {
    title: "Prescripción adquisitiva",
    status: "abierto",
    category: "civil",
    urgency: "baja",
    description: "Solicitud de prescripción de propiedad",
  },
  {
    title: "Rectificación de partida",
    status: "abierto",
    category: "civil",
    urgency: "baja",
    description: "Rectificación de datos en partida de nacimiento",
  },
  {
    title: "Difamación",
    status: "abierto",
    category: "penal",
    urgency: "media",
    description: "Denuncia por difamación en redes sociales",
  },
  {
    title: "Lesiones graves",
    status: "abierto",
    category: "penal",
    urgency: "alta",
    description: "Denuncia por lesiones con incapacidad",
  },
  {
    title: "Separación de bienes",
    status: "abierto",
    category: "familiar",
    urgency: "media",
    description: "Proceso de separación patrimonial",
  },
  {
    title: "Reconocimiento de paternidad",
    status: "abierto",
    category: "familiar",
    urgency: "alta",
    description: "Proceso de filiación",
  },
  {
    title: "Discriminación laboral",
    status: "abierto",
    category: "laboral",
    urgency: "media",
    description: "Denuncia por discriminación en el trabajo",
  },
  {
    title: "Indemnización por despido",
    status: "abierto",
    category: "laboral",
    urgency: "alta",
    description: "Reclamación de indemnización",
  },
  {
    title: "Nulidad de contrato",
    status: "abierto",
    category: "civil",
    urgency: "media",
    description: "Solicitud de nulidad contractual",
  },
  {
    title: "Servidumbre de paso",
    status: "abierto",
    category: "civil",
    urgency: "baja",
    description: "Establecimiento de servidumbre",
  },
  {
    title: "Apropiación ilícita",
    status: "abierto",
    category: "penal",
    urgency: "alta",
    description: "Denuncia por apropiación indebida",
  },
  {
    title: "Violación de domicilio",
    status: "abierto",
    category: "penal",
    urgency: "media",
    description: "Denuncia por ingreso ilegal a propiedad",
  },
];

// Lawyer seed data
export const LAWYER_CASES_LIST = [
  {
    title: "Demanda por incumplimiento contractual",
    status: "en_progreso",
    category: "civil",
    urgency: "alta",
    description: "Cliente demanda a empresa por incumplimiento de contrato de servicios",
  },
  {
    title: "Defensa en juicio laboral",
    status: "abierto",
    category: "laboral",
    urgency: "alta",
    description: "Defensa de trabajador en proceso de despido arbitrario",
  },
  {
    title: "Divorcio por mutuo acuerdo",
    status: "en_progreso",
    category: "familiar",
    urgency: "media",
    description: "Trámite de divorcio consensuado con liquidación de bienes",
  },
  {
    title: "Querella por difamación",
    status: "abierto",
    category: "penal",
    urgency: "alta",
    description: "Querella criminal por difamación en medios digitales",
  },
  {
    title: "Reclamación de herencia",
    status: "en_progreso",
    category: "civil",
    urgency: "media",
    description: "Proceso sucesorio con múltiples herederos",
  },
  {
    title: "Demanda por accidente de tránsito",
    status: "abierto",
    category: "civil",
    urgency: "alta",
    description: "Indemnización por daños y perjuicios en accidente vehicular",
  },
  {
    title: "Proceso de adopción internacional",
    status: "en_progreso",
    category: "familiar",
    urgency: "baja",
    description: "Trámite de adopción de menor extranjero",
  },
  {
    title: "Defensa por fraude fiscal",
    status: "abierto",
    category: "penal",
    urgency: "alta",
    description: "Defensa en proceso penal por evasión tributaria",
  },
  {
    title: "Negociación colectiva",
    status: "en_progreso",
    category: "laboral",
    urgency: "media",
    description: "Asesoría en negociación colectiva de sindicato",
  },
  {
    title: "Desalojo por ocupación precaria",
    status: "abierto",
    category: "civil",
    urgency: "alta",
    description: "Proceso de desalojo de inmueble ocupado ilegalmente",
  },
  {
    title: "Pensión de alimentos para mayores",
    status: "cerrado",
    category: "familiar",
    urgency: "media",
    description: "Proceso de pensión alimenticia para hijos mayores de edad",
  },
  {
    title: "Denuncia por acoso sexual",
    status: "en_progreso",
    category: "penal",
    urgency: "alta",
    description: "Denuncia penal por acoso sexual en el trabajo",
  },
  {
    title: "Reclamo por despido colectivo",
    status: "abierto",
    category: "laboral",
    urgency: "alta",
    description: "Defensa de grupo de trabajadores despedidos",
  },
  {
    title: "Nulidad de testamento",
    status: "en_progreso",
    category: "civil",
    urgency: "media",
    description: "Impugnación de testamento por vicios de forma",
  },
  {
    title: "Régimen de visitas internacional",
    status: "abierto",
    category: "familiar",
    urgency: "alta",
    description: "Establecimiento de régimen de visitas con menor en el extranjero",
  },
  {
    title: "Defensa por delito informático",
    status: "en_progreso",
    category: "penal",
    urgency: "media",
    description: "Defensa en proceso por hackeo y robo de información",
  },
  {
    title: "Reclamación de utilidades",
    status: "cerrado",
    category: "laboral",
    urgency: "baja",
    description: "Reclamo por pago incompleto de utilidades anuales",
  },
  {
    title: "Prescripción adquisitiva de dominio",
    status: "en_progreso",
    category: "civil",
    urgency: "baja",
    description: "Proceso de usucapión de propiedad inmueble",
  },
  {
    title: "Violencia familiar con medidas de protección",
    status: "abierto",
    category: "familiar",
    urgency: "alta",
    description: "Proceso de violencia familiar con solicitud de medidas cautelares",
  },
  {
    title: "Querella por estafa agravada",
    status: "en_progreso",
    category: "penal",
    urgency: "alta",
    description: "Querella criminal por estafa en inversiones fraudulentas",
  },
];

export const EXTERNAL_CLIENTS_LIST = [
  {
    full_name: "María González Rodríguez",
    email: "maria.gonzalez@email.com",
    phone: "+51987654321",
    dni: "12345678",
  },
  {
    full_name: "Carlos Mendoza Silva",
    email: "carlos.mendoza@email.com",
    phone: "+51987654322",
    dni: "23456789",
  },
  {
    full_name: "Ana Patricia Flores",
    email: "ana.flores@email.com",
    phone: "+51987654323",
    dni: "34567890",
  },
  {
    full_name: "Roberto Sánchez Torres",
    email: "roberto.sanchez@email.com",
    phone: "+51987654324",
    dni: "45678901",
  },
  {
    full_name: "Laura Martínez Vega",
    email: "laura.martinez@email.com",
    phone: "+51987654325",
    dni: "56789012",
  },
  {
    full_name: "Diego Ramírez Castro",
    email: "diego.ramirez@email.com",
    phone: "+51987654326",
    dni: "67890123",
  },
  {
    full_name: "Carmen López Herrera",
    email: "carmen.lopez@email.com",
    phone: "+51987654327",
    dni: "78901234",
  },
  {
    full_name: "Fernando Gutiérrez Mora",
    email: "fernando.gutierrez@email.com",
    phone: "+51987654328",
    dni: "89012345",
  },
  {
    full_name: "Patricia Rojas Delgado",
    email: "patricia.rojas@email.com",
    phone: "+51987654329",
    dni: "90123456",
  },
  {
    full_name: "Miguel Ángel Vargas",
    email: "miguel.vargas@email.com",
    phone: "+51987654330",
    dni: "01234567",
  },
  {
    full_name: "Sofía Castillo Núñez",
    email: "sofia.castillo@email.com",
    phone: "+51987654331",
    dni: "11234568",
  },
  {
    full_name: "Javier Morales Quispe",
    email: "javier.morales@email.com",
    phone: "+51987654332",
    dni: "21234569",
  },
  {
    full_name: "Gabriela Paredes Luna",
    email: "gabriela.paredes@email.com",
    phone: "+51987654333",
    dni: "31234570",
  },
  {
    full_name: "Ricardo Fernández Díaz",
    email: "ricardo.fernandez@email.com",
    phone: "+51987654334",
    dni: "41234571",
  },
  {
    full_name: "Valeria Campos Ramos",
    email: "valeria.campos@email.com",
    phone: "+51987654335",
    dni: "51234572",
  },
  {
    full_name: "Andrés Salazar Pinto",
    email: "andres.salazar@email.com",
    phone: "+51987654336",
    dni: "61234573",
  },
  {
    full_name: "Daniela Ortiz Medina",
    email: "daniela.ortiz@email.com",
    phone: "+51987654337",
    dni: "71234574",
  },
  {
    full_name: "Pablo Navarro Chávez",
    email: "pablo.navarro@email.com",
    phone: "+51987654338",
    dni: "81234575",
  },
  {
    full_name: "Mónica Reyes Aguilar",
    email: "monica.reyes@email.com",
    phone: "+51987654339",
    dni: "91234576",
  },
  {
    full_name: "Héctor Jiménez Soto",
    email: "hector.jimenez@email.com",
    phone: "+51987654340",
    dni: "10234577",
  },
  {
    full_name: "Isabel Romero Paz",
    email: "isabel.romero@email.com",
    phone: "+51987654341",
    dni: "20234578",
  },
  {
    full_name: "Sergio Vásquez Cruz",
    email: "sergio.vasquez@email.com",
    phone: "+51987654342",
    dni: "30234579",
  },
  {
    full_name: "Natalia Herrera Ríos",
    email: "natalia.herrera@email.com",
    phone: "+51987654343",
    dni: "40234580",
  },
  {
    full_name: "Alejandro Peña Montes",
    email: "alejandro.pena@email.com",
    phone: "+51987654344",
    dni: "50234581",
  },
  {
    full_name: "Claudia Espinoza Vera",
    email: "claudia.espinoza@email.com",
    phone: "+51987654345",
    dni: "60234582",
  },
];
