export const CATEGORIES = ["civil", "laboral", "familiar", "penal"];
export const STATUSES = ["abierto", "en_progreso", "cerrado", "archivado"];
export const CLIENT_CASES_LIST = [
  {
    title: "Divorcio contencioso",
    status: "abierto",
    category: "familiar",
    urgency: "alta",
    description: "Proceso de divorcio con disputa de bienes",
  },
  {
    title: "Pensión alimenticia",
    status: "abierto",
    category: "familiar",
    urgency: "alta",
    description: "Solicitud de pensión alimenticia para menores",
  },
  {
    title: "Custodia de menores",
    status: "abierto",
    category: "familiar",
    urgency: "media",
    description: "Disputa por custodia compartida",
  },
  {
    title: "Despido injustificado",
    status: "abierto",
    category: "laboral",
    urgency: "alta",
    description: "Reclamación por despido sin causa justa",
  },
  {
    title: "Accidente laboral",
    status: "abierto",
    category: "laboral",
    urgency: "media",
    description: "Indemnización por accidente en el trabajo",
  },
  {
    title: "Horas extras no pagadas",
    status: "abierto",
    category: "laboral",
    urgency: "baja",
    description: "Reclamación de horas extras trabajadas",
  },
  {
    title: "Contrato de arrendamiento",
    status: "abierto",
    category: "civil",
    urgency: "media",
    description: "Disputa por contrato de alquiler",
  },
  {
    title: "Daños y perjuicios",
    status: "abierto",
    category: "civil",
    urgency: "alta",
    description: "Reclamación por daños materiales",
  },
  {
    title: "Incumplimiento de contrato",
    status: "abierto",
    category: "civil",
    urgency: "media",
    description: "Incumplimiento de contrato comercial",
  },
  {
    title: "Herencia y sucesiones",
    status: "abierto",
    category: "civil",
    urgency: "baja",
    description: "Proceso de sucesión testamentaria",
  },
  {
    title: "Denuncia por robo",
    status: "abierto",
    category: "penal",
    urgency: "alta",
    description: "Denuncia penal por robo con violencia",
  },
  {
    title: "Estafa comercial",
    status: "abierto",
    category: "penal",
    urgency: "media",
    description: "Denuncia por estafa en transacción comercial",
  },
  {
    title: "Violencia doméstica",
    status: "abierto",
    category: "penal",
    urgency: "alta",
    description: "Denuncia por violencia intrafamiliar",
  },
  {
    title: "Régimen de visitas",
    status: "abierto",
    category: "familiar",
    urgency: "media",
    description: "Establecimiento de régimen de visitas",
  },
  {
    title: "Adopción",
    status: "abierto",
    category: "familiar",
    urgency: "baja",
    description: "Proceso de adopción de menor",
  },
  {
    title: "Hostigamiento laboral",
    status: "abierto",
    category: "laboral",
    urgency: "alta",
    description: "Denuncia por acoso en el trabajo",
  },
  {
    title: "Liquidación de beneficios",
    status: "abierto",
    category: "laboral",
    urgency: "media",
    description: "Reclamación de beneficios sociales",
  },
  {
    title: "Desalojo",
    status: "abierto",
    category: "civil",
    urgency: "alta",
    description: "Proceso de desalojo de inmueble",
  },
  {
    title: "Prescripción adquisitiva",
    status: "abierto",
    category: "civil",
    urgency: "baja",
    description: "Solicitud de prescripción de propiedad",
  },
  {
    title: "Rectificación de partida",
    status: "abierto",
    category: "civil",
    urgency: "baja",
    description: "Rectificación de datos en partida de nacimiento",
  },
  {
    title: "Difamación",
    status: "abierto",
    category: "penal",
    urgency: "media",
    description: "Denuncia por difamación en redes sociales",
  },
  {
    title: "Lesiones graves",
    status: "abierto",
    category: "penal",
    urgency: "alta",
    description: "Denuncia por lesiones con incapacidad",
  },
  {
    title: "Separación de bienes",
    status: "abierto",
    category: "familiar",
    urgency: "media",
    description: "Proceso de separación patrimonial",
  },
  {
    title: "Reconocimiento de paternidad",
    status: "abierto",
    category: "familiar",
    urgency: "alta",
    description: "Proceso de filiación",
  },
  {
    title: "Discriminación laboral",
    status: "abierto",
    category: "laboral",
    urgency: "media",
    description: "Denuncia por discriminación en el trabajo",
  },
  {
    title: "Indemnización por despido",
    status: "abierto",
    category: "laboral",
    urgency: "alta",
    description: "Reclamación de indemnización",
  },
  {
    title: "Nulidad de contrato",
    status: "abierto",
    category: "civil",
    urgency: "media",
    description: "Solicitud de nulidad contractual",
  },
  {
    title: "Servidumbre de paso",
    status: "abierto",
    category: "civil",
    urgency: "baja",
    description: "Establecimiento de servidumbre",
  },
  {
    title: "Apropiación ilícita",
    status: "abierto",
    category: "penal",
    urgency: "alta",
    description: "Denuncia por apropiación indebida",
  },
  {
    title: "Violación de domicilio",
    status: "abierto",
    category: "penal",
    urgency: "media",
    description: "Denuncia por ingreso ilegal a propiedad",
  },
];
